shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from user.views import testing_index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', testing_index, name='test-page'),

    path('products/', include('product.urls')),
    path('user/', include('user.urls')),
    path('cart/', include('cart11.urls')),
    path('order/', include('payment.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('profile/<int:id>', views.user_profile, name='profile'),

    path('changePassword/<int:id>',
         views.change_password, name='change-password')
]

templates/base.htm
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>

    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

    <!-- Font Awesome CDN -->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">



    {% block head %}{% endblock %}

    <style type="text/css">
        .category-nav {
            flex: 1;
            margin: auto !important;
            display: flex;
            justify-content: space-around;
        }

        #header-nav {
            flex: 1;
            margin: auto !important;
            display: flex;
            justify-content: end;
        }
    </style>

</head>

<body>
    {% block content %} {% endblock %}
</body>

</html>

templates/category_nav.htm
<div class="navbar navbar-expand-lg navbar-dark bg-dark mb-4" role="navigation">

    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto category-nav">
            <li class="nav-item dropdown border-right-white">
                <a class="nav-link dropdown-toggle" id="dropdown1" data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false" href="#">Electronics</a>
                <ul class="dropdown-menu" aria-labelledby="dropdown1">
                    <li class="dropdown-item" href="#"><a href="#">Laptops</a></li>
                    <li class="dropdown-item" href="#"><a href="#">Mobiles</a></li>
                    <li class="dropdown-item" href="#"><a href="#">Mobile Acessories</a></li>
                    <li class="dropdown-item" href="#"><a href="#">Television</a></li>
                </ul>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="dropdown1" data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false" href="#">Men</a>
                <ul class="dropdown-menu" aria-labelledby="dropdown1">
                    <li class="dropdown-item" href="#"><a href="#">Footwear</a></li>
                    <li class="dropdown-item" href="#"><a href="#">Clothing</a></li>
                    <li class="dropdown-item" href="#"><a href="#">Ethnic wear</a></li>
                    <li class="dropdown-item" href="#"><a href="#">Beauty & Grooming</a></li>
                </ul>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="dropdown1" data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false" href="#">Women</a>
                <ul class="dropdown-menu" aria-labelledby="dropdown1">
                    <li class="dropdown-item" href="#"><a href="#">Footwear</a></li>
                    <li class="dropdown-item" href="#"><a href="#">Clothing</a></li>
                    <li class="dropdown-item" href="#"><a href="#">Ethnic wear</a></li>
                    <li class="dropdown-item" href="#"><a href="#">Beauty & Grooming</a></li>
                </ul>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="dropdown1" data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false" href="#">Baby & Kids</a>
                <ul class="dropdown-menu" aria-labelledby="dropdown1">
                    <li class="dropdown-item" href="#"><a href="#">Clothing</a></li>
                    <li class="dropdown-item" href="#"><a href="#">Footwear</a></li>
                    <li class="dropdown-item" href="#"><a href="#">Toys</a></li>
                    <li class="dropdown-item" href="#"><a href="#">Baby category-nav</a></li>
                </ul>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="dropdown1" data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false" href="#">TVs & Appliances</a>
                <ul class="dropdown-menu" aria-labelledby="dropdown1">
                    <li class="dropdown-item" href="#"><a href="#">Televisions</a></li>
                    <li class="dropdown-item" href="#"><a href="#">Refrigerators</a></li>
                    <li class="dropdown-item" href="#"><a href="#">Washing Machines</a></li>
                </ul>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="dropdown1" data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false" href="#">Health & Nutrition</a>
                <ul class="dropdown-menu" aria-labelledby="dropdown1">
                    <li class="dropdown-item" href="#"><a href="#">All Products</a></li>
                    <li class="dropdown-item" href="#"><a href="#">Protein</a></li>
                    <li class="dropdown-item" href="#"><a href="#">Vitamin</a></li>
                    <li class="dropdown-item" href="#"><a href="#">Health Drinks</a></li>
                </ul>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="dropdown1" data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false" href="#">Home & Furniture</a>
                <ul class="dropdown-menu" aria-labelledby="dropdown1">
                    <li class="dropdown-item" href="#"><a href="#">Kitchen and Cookwear</a></li>
                    <li class="dropdown-item" href="#"><a href="#">Furniture</a></li>
                    <li class="dropdown-item" href="#"><a href="#">Furnishing</a></li>
                    <li class="dropdown-item" href="#"><a href="#">Home Decor</a></li>
                </ul>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="dropdown1" data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false" href="#">Sports & Books</a>
                <ul class="dropdown-menu" aria-labelledby="dropdown1">
                    <li class="dropdown-item" href="#"><a href="#">Sports Accessories</a></li>
                    <li class="dropdown-item" href="#"><a href="#">Fitness</a></li>
                    <li class="dropdown-item" href="#"><a href="#">Entrance Books</a></li>
                    <li class="dropdown-item" href="#"><a href="#">Novels</a></li>
                </ul>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="dropdown1" data-toggle="dropdown" aria-haspopup="true"
                    aria-expanded="false" href="#">Gaming & Music</a>
                <ul class="dropdown-menu" aria-labelledby="dropdown1">
                    <li class="dropdown-item" href="#"><a href="#">Music Instruments</a></li>
                    <li class="dropdown-item" href="#"><a href="#">Music</a></li>
                    <li class="dropdown-item" href="#"><a href="#">Gaming Console</a></li>
                    <li class="dropdown-item" href="#"><a href="#">Gaming Accessories</a></li>
                </ul>
            </li>
        </ul>
    </div>
</div>

templates/footer.htm
<!-- Footer -->
<footer class="page-footer font-small stylish-color-dark pt-4 bg-dark text-light">

  <!-- Footer Links -->
  <div class="container text-center text-md-left">

    <!-- Grid row -->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-4 mx-auto">

        <!-- Content -->
        <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Mail Us:</h5>
        <p>Shopper's Bay Private Limited, <br> Buildings xyz <br> pqr Tech Village,<br> Abc Road,<br>
            New Delhi, 000000,<br> India.</p>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none">

      <!-- Grid column -->
      <div class="col-md-2 mx-auto">

        <!-- Links -->
        <h5 class="font-weight-bold text-uppercase mt-3 mb-4">About us</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!">Contact Us</a>
          </li>
          <li>
            <a href="#!">About Us</a>
          </li>
          <li>
            <a href="#!">Shipping</a>
          </li>
          <li>
            <a href="#!">Payment</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none">

      <!-- Grid column -->
      <div class="col-md-2 mx-auto">

        <!-- Links -->
        <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Policies</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!">Return Policy</a>
          </li>
          <li>
            <a href="#!">Security</a>
          </li>
          <li>
            <a href="#!">Privacy</a>
          </li>
          <li>
            <a href="#!">Term of use</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none">

      <!-- Grid column -->
      <div class="col-md-2 mx-auto">

        <!-- Links -->
        <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Social</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!">Facebook</a>
          </li>
          <li>
            <a href="#!">Twitter</a>
          </li>
          <li>
            <a href="#!">Instagram</a>
          </li>
          <li>
            <a href="#!">Linkedin</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <hr>

  <!-- Call to action -->
  <ul class="list-unstyled list-inline text-center py-2">
    <li class="list-inline-item">
      <h5 class="mb-1">Register for free</h5>
    </li>
    <li class="list-inline-item">
      <a href="{% url 'user:signup' %}" class="btn btn-danger btn-rounded">Sign up!</a>
    </li>
  </ul>
  <!-- Call to action -->

  <hr>

  <!-- Social buttons -->
  <ul class="list-unstyled list-inline text-center">
    <li class="list-inline-item">
      <a class="btn-floating btn-fb mx-1">
        <i class="fa fa-facebook text-light"> </i>
      </a>
    </li>
    <li class="list-inline-item">
      <a class="btn-floating btn-tw mx-1">
        <i class="fa fa-twitter"> </i>
      </a>
    </li>
    <li class="list-inline-item">
      <a class="btn-floating btn-gplus mx-1">
        <i class="fa fa-google-plus"> </i>
      </a>
    </li>
    <li class="list-inline-item">
      <a class="btn-floating btn-li mx-1">
        <i class="fa fa-linkedin"> </i>
      </a>
    </li>
    <li class="list-inline-item">
      <a class="btn-floating btn-dribbble mx-1">
        <i class="fa fa-dribbble"> </i>
      </a>
    </li>
  </ul>
  <!-- Social buttons -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2018 Copyright:
    <a href="#"> Akshay Kumar </a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

templates/header_nav.htm
<div class="navbar navbar-expand-lg navbar-dark bg-dark " role="navigation">
    <a class="navbar-brand" href="{% url 'products-page' %}">Shopper's Bay</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
        aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto" id="header-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'user:login' %}"></a>
            </li>

        </ul>
        <form class="form-inline mt-2 mt-md-0" method="POST"> {% csrf_token %}
            <input class="form-control mr-sm-2" type="text" placeholder="Search for product, brand or category"
                aria-label="Search" style="width: 350px;" name="txtSearch">
            <button class="btn btn-outline-success my-2 my-sm-0 mr-4" type="submit" name='btnSearch'>Search</button>
        </form>
        &nbsp;&nbsp;&nbsp;&nbsp;

        <ul class="navbar-nav" id="header-nav1">
            {%if not profile %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'user:login' %}">Login</a>
            </li>
            {%endif%}
            {% if profile %}
            <div class="nav">

                <li class="navbar-item dropdown ">
                    <a href="." class="navbar-link dropdown-toggle text-light" id="dropdown1" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false" style="text-decoration: none;">

                        {{profile}}

                    </a>

                    <ul class="dropdown-menu" aria-labelledby="dropdown1">
                        <li class="dropdown-item">
                            <a href="{% url 'user:profile' user.id %}">Profile</a>
                        </li>
                        <li class="dropdown-item">
                            <a href="">Orders</a>
                        </li>
                        <li class="dropdown-item">
                            <a href="">Wishlist</a>
                        </li>
                        <li class="dropdown-item">
                            <a href="{% url 'user:logout' %}">Logout</a>
                        </li>
                    </ul>-
                </li>
                <li>
                    {% if profile %}
                    <a href="{% url 'cart' %}" class="btn btn-info  mr-5 ml-5">
                        <i class="fa fa-cart-arrow-down" aria-hidden="true"></i>
                        CART <span class="badge badge-danger">{{ cart_no }}</span>
                    </a>
                    {% endif %}
                </li>

                {%endif%}
            </div>
            <div class="nav">

            </div>

        </ul>

    </div>

</div>

templates/side_nav.htm
<!-- Sidebar -->
<nav id="sidebar">
    <div class="sidebar-header">
        <h3></h3>
    </div>

    <ul class="list-unstyled components">
        <p>Categories</p>
        <li class="active">
            <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Home</a>
            <ul class="collapse list-unstyled" id="homeSubmenu">
                <li>
                    <a href="#">Home 1</a>
                </li>
                <li>
                    <a href="#">Home 2</a>
                </li>
                <li>
                    <a href="#">Home 3</a>
                </li>
            </ul>
        </li>
        <li>
            <a href="#">About</a>
        </li>
        <li>
            <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Pages</a>
            <ul class="collapse list-unstyled" id="pageSubmenu">
                <li>
                    <a href="#">Page 1</a>
                </li>
                <li>
                    <a href="#">Page 2</a>
                </li>
                <li>
                    <a href="#">Page 3</a>
                </li>
            </ul>
        </li>
        <li>
            <a href="#">Portfolio</a>
        </li>
        <li>
            <a href="#">Contact</a>
        </li>
    </ul>
</nav>